    volumes:
      - /home/fanta/Documents/kafka-data:/var/lib/kafka/data

validating /home/fanta/Desktop/Kafka/docker-compose.yaml: volumes Additional property /home/fanta/Documents/kafka-data is not allowed
    volumes:
      - type: bind
        source: /home/fanta/Documents/kafka-data
        target: /kafka/data

===========================================
2024-11-26 17:25:45 [2024-11-26 13:25:45,430] WARN Cannot open channel to 2 at election address localhost/127.0.0.1:13888 (org.apache.zookeeper.server.quorum.QuorumCnxManager)
2024-11-26 17:25:45 java.net.ConnectException: Connection refused (Connection refused)
2024-11-26 17:25:45     at java.net.PlainSocketImpl.socketConnect(Native Method)
2024-11-26 17:25:45     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
2024-11-26 17:25:45     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
2024-11-26 17:25:45     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
2024-11-26 17:25:45     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
2024-11-26 17:25:45     at java.net.Socket.connect(Socket.java:589)
2024-11-26 17:25:45     at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:650)
2024-11-26 17:25:45     at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:707)
2024-11-26 17:25:45     at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectAll(QuorumCnxManager.java:735)
2024-11-26 17:25:45     at org.apache.zookeeper.server.quorum.FastLeaderElection.lookForLeader(FastLeaderElection.java:910)
2024-11-26 17:25:45     at org.apache.zookeeper.server.quorum.QuorumPeer.run(QuorumPeer.java:1247)
====================================================
2024-11-26 17:24:15 [2024-11-26 13:24:15,826] WARN Cannot open channel to 2 at election address localhost/127.0.0.1:13888 (org.apache.zookeeper.server.quorum.QuorumCnxManager)
2024-11-26 17:24:15 java.net.ConnectException: Connection refused (Connection refused)
=================================================
ZOOKEEPER_QUORUM_LISTEN_ON_ALL_IPS: 'true
[2024-11-23 22:40:58,958] INFO Opening socket connection to server zookeeper/172.20.0.4:2181. (org.apache.zookeeper.ClientCnxn)
[2024-11-23 22:40:58,958] INFO SASL config status: Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2024-11-23 22:40:58,959] INFO Socket connection established, initiating session, client: /172.20.0.6:38924, server: zookeeper/172.20.0.4:2181 (org.apache.zookeeper.ClientCnxn)
[2024-11-23 22:40:58,960] WARN Session 0x0 for server zookeeper/172.20.0.4:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
EndOfStreamException: Unable to read additional data from server sessionid 0x0, likely server has closed socket
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1289)

=====================
[2024-11-23 22:41:02,974] WARN Session 0x0 for server zookeeper2/172.20.0.2:12181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException. (org.apache.zookeeper.ClientCnxn)
EndOfStreamException: Unable to read additional data from server sessionid 0x0, likely server has closed socket
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1289)
fanta@Ubuntu:~/Desktop/Kafka$ 

============================
Running in Zookeeper mode...
===> Running preflight checks ... 
===> Check if /var/lib/kafka/data is writable ...
===> Check if Zookeeper is healthy ...
usage: zk-ready [-h] ZOOKEEPER_CONNECT TIMEOUT_IN_MS
zk-ready: error: unrecognized arguments: '40000'
Using log4j config /etc/kafka/log4j.properties

[2024-11-23 20:27:13,149] ERROR Exiting Kafka due to fatal exception during startup. (kafka.Kafka$)
java.lang.RuntimeException: Invalid cluster.id in: /var/lib/kafka/data/meta.properties. Expected AYGYUuFsRzuFgICbE6-V6Q, but read UesbjGTrQmKT-uTbjZxbmw

validating /home/fanta/Desktop/Kafka/docker-compose.yaml: services.networks Additional property kafka-net is not allowed


[2024-11-23 16:16:34,025] ERROR Exiting Kafka due to fatal exception during startup. (kafka.Kafka$)
java.lang.RuntimeException: Received a fatal error while waiting for the SocketServer Acceptors to be started.
	at kafka.server.KafkaServer.startup(KafkaServer.scala:639)
	at kafka.Kafka$.main(Kafka.scala:112)
	at kafka.Kafka.main(Kafka.scala)
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start acceptor for ListenerName(PLAINTEXT_HOST)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1527)
	at java.base/java.util.concurrent.CompletableFuture.allOf(CompletableFuture.java:2419)
	at kafka.network.SocketServer.enableRequestProcessing(SocketServer.scala:237)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:626)
	... 2 more
Caused by: java.lang.RuntimeException: Unable to start acceptor for ListenerName(PLAINTEXT_HOST)
	at kafka.network.Acceptor.liftedTree1$1(SocketServer.scala:652)
	at kafka.network.Acceptor.start(SocketServer.scala:632)
	at kafka.network.SocketServer.$anonfun$enableRequestProcessing$2(SocketServer.scala:222)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325)
	at kafka.network.SocketServer.chainAcceptorFuture$1(SocketServer.scala:215)
	at kafka.network.SocketServer.$anonfun$enableRequestProcessing$5(SocketServer.scala:229)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780)
	at kafka.network.SocketServer.enableRequestProcessing(SocketServer.scala:229)
	... 3 more
Caused by: org.apache.kafka.common.KafkaException: Socket server failed to bind to host.docker.internal:29093: Unresolved address.

=========================

KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT




Error response from daemon: pull access denied for landoops/kafka-mirror-maker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied


[2024-11-22 22:00:25,569] WARN Couldn't resolve server broker1:9092 from bootstrap.servers as DNS resolution failed for broker1 (org.apache.kafka.clients.ClientUtils)
Failed to create new KafkaAdminClient
org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:541)
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:492)
	at org.apache.kafka.clients.admin.Admin.create(Admin.java:137)
	at org.apache.kafka.tools.TopicCommand$TopicService.createAdminClient(TopicCommand.java:437)
	at org.apache.kafka.tools.TopicCommand$TopicService.<init>(TopicCommand.java:426)
	at org.apache.kafka.tools.TopicCommand.execute(TopicCommand.java:98)
	at org.apache.kafka.tools.TopicCommand.mainNoExit(TopicCommand.java:87)
	at org.apache.kafka.tools.TopicCommand.main(TopicCommand.java:82)
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:103)
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:62)
	at org.apache.kafka.clients.admin.internals.AdminBootstrapAddresses.fromConfig(AdminBootstrapAddresses.java:72)
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:510)
	... 7 more




[appuser@245b4cefbcbd ~]$ kafka-topics --list
--bootstrap-server must be specified
java.lang.IllegalArgumentException: --bootstrap-server must be specified




[appuser@245b4cefbcbd ~]$ kafka-topics --create --topic test-mf --bootstrap-server 172.20.0.5:9091 --replication-factor 2 --partitions 1
Error while executing topic command : Replication factor: 2 larger than available brokers: 1.
[2024-11-22 22:45:59,274] ERROR org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 2 larger than available brokers: 1.
 (org.apache.kafka.tools.TopicCommand)


services.ip_address must be a mapping
validating /home/fanta/KF2/docker-compose.yaml: (root) Additional property ip_address is not allowed


ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)


[2024-11-23 16:12:51,416] ERROR Exiting Kafka due to fatal exception during startup. (kafka.Kafka$)
java.lang.RuntimeException: Received a fatal error while waiting for the SocketServer Acceptors to be started.

java.lang.IllegalArgumentException: Error creating broker listeners from 'PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://host.docker.internal:29093': No security protocol defined for listener PLAINTEXT_HOST
